# Distinct development Dockerfile for frontend to run dev server and enable hot-reloading.
# Useful for local development, to use docker compose watch.

FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Expose port
EXPOSE 80

# Run dev server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "80"]
